sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
gemfile:
  - gemfiles/sprockets3.gemfile
  - gemfiles/sprockets4.gemfile
branches:
  only:
    - master
before_install:
  - gem update --system 2.7.9 --no-doc
after_script:
  - '[ ${TRAVIS_EVENT_TYPE} != "pull_request" ] && [ ${TRAVIS_BRANCH} = "master" ] && bundle exec codeclimate-test-reporter'
