sudo: false
language: ruby
rvm:
  - 2.2.2
  - 2.3.1
gemfile:
  - gemfiles/sprockets3.gemfile
  - gemfiles/sprockets4.gemfile
branches:
  only:
    - master
after_script:
  - '[ ${TRAVIS_EVENT_TYPE} != "pull_request" ] && [ ${TRAVIS_BRANCH} = "master" ] && bundle exec codeclimate-test-reporter'
